#spring:
#  datasource:
#    username: sa
#    password: sa
#    url: jdbc:h2:file:~/jpadb
#    driver-class-name: org.h2.Driver
#    schema:
#      - classpath:schema.sql
#      - classpath:data.sql
#    initialization-mode: always

spring:
  datasource:
    username: sa
    password: sa
    url: jdbc:h2:~/t2;AUTO_SERVER=TRUE
#    url: jdbc:h2:mem:default
    driver-class-name: org.h2.Driver
    schema:
      - classpath:schema.sql
    #      - classpath:data.sql
    initialization-mode: always